name: Certora Prover 

on:
  push:
    branches:
      - kel/specs
      - certora
  pull_request:
  workflow_dispatch:

jobs:
  certora_run_health:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install sui
        run: |
          curl -sSfL https://raw.githubusercontent.com/Mystenlabs/suiup/main/install.sh | sh
          export PATH="$HOME/.local/bin:$PATH"
          suiup install -y sui@testnet
      - name: Apply patch
        run: ./certora/munges/munge.sh
      - name: Submit Jobs to Certora Prover
        uses: Certora/certora-run-action@v2
        with:
          ecosystem: sui
          working-directory: certora/spec/
          configurations: |-
            confs/consistency.conf
            confs/integrity.conf
            confs/solvency.conf
          job-name: "Verify Obligation Health Rules"
          certora-key: ${{ secrets.CERTORAKEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}